# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=128)),
                ('mode', models.IntegerField(choices=[(0, 'darf nicht'), (1, 'kann'), (2, 'muss')])),
                ('description', models.CharField(max_length=2048)),
                ('rule', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('comma_select', models.CommaSeparatedIntegerField(default='0', max_length=255)),
                ('total_submits', models.IntegerField(default='0', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Rule')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Sentence')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('solution', models.BigIntegerField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Sentence')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_rank', models.IntegerField(choices=[(0, 'Kommachaot'), (1, 'Kommakönner'), (2, 'Kommakommandant'), (3, 'Kommakönig')], default=0)),
                ('comma_type_false', models.CharField(default='A1:0/0, A2:0/0, A3:0/0, A4:0/0, B1.1:0/0, B1.2:0/0, B1.3:0/0, B1.4.1:0/0, B1.4.2:0/0, B1.5:0/0, B2.1:0/0, B2.2:0/0, B2.3:0/0, B2.4.1:0/0, B2.4.2:0/0, B2.5:0/0, C1:0/0, C2:0/0, C3.1:0/0, C3.2:0/0, C4.1:0/0, C4.2:0/0, C5:0/0, C6.1:0/0, C6.2:0/0, C6.3.1:0/0, C6.3.2:0/0, C6.4:0/0, C7:0/0, C8:0/0, D1:0/0, D2:0/0, D3:0/0, E1:0/0', max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='rules',
            field=models.ManyToManyField(through='trainer.SentenceRule', to='trainer.Rule'),
        ),
    ]
