# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rules_activated_count',
            field=models.IntegerField(default=0),
        ),
    ]
