# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20161116_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Rule')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Sentence')),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='rules',
            field=models.ManyToManyField(through='trainer.SentenceRule', to='trainer.Rule'),
        ),
    ]
