# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_auto_20170508_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='user_id',
            new_name='user',
        ),
    ]
