# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20170508_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='data',
            field=models.CharField(default='', max_length=255),
        ),
    ]
