# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_rule_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='data',
        ),
        migrations.AddField(
            model_name='user',
            name='data',
            field=models.CharField(default='', max_length=255),
        ),
    ]
