# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_auto_20170519_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='time_elapsed',
            field=models.IntegerField(default=0),
        ),
    ]
