# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_solution_time_elapsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='counter_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='counter_wrong',
            field=models.IntegerField(default=0),
        ),
    ]
