# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_auto_20170523_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='comma_select',
        ),
        migrations.AlterField(
            model_name='sentence',
            name='total_submits',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='usersentence',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Sentence'),
        ),
        migrations.AddField(
            model_name='usersentence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='sentences',
            field=models.ManyToManyField(through='trainer.UserSentence', to='trainer.Sentence'),
        ),
    ]
