# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_auto_20170523_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersentence',
            options={'ordering': ('count',)},
        ),
        migrations.AlterField(
            model_name='usersentence',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_user', to='trainer.Sentence'),
        ),
    ]
