# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0011_auto_20170524_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='example',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='rule',
            name='paragraph',
            field=models.CharField(default='', max_length=255),
        ),
    ]
