# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0014_user_django_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_l1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='data_selfestimation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='data_semester',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='data_sex',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='data_study',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='data_study_permission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='data_subject1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='data_subject2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='data_subject3',
            field=models.IntegerField(default=0),
        ),
    ]
