# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0015_auto_20170602_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sentencerule',
            name='pair',
            field=models.IntegerField(default=0),
        ),
    ]
