# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0016_auto_20170603_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.BooleanField(default=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Rule')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Solution')),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='rules',
            field=models.ManyToManyField(through='trainer.SolutionRule', to='trainer.Rule'),
        ),
    ]
