# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0018_user_data_orthosem_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_rank',
        ),
        migrations.AddField(
            model_name='user',
            name='strategy',
            field=models.IntegerField(choices=[(0, 'Leitnerbox'), (1, 'Bayes')], default=0),
        ),
    ]
