# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0020_auto_20180504_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrule',
            name='dynamicnet_count1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrule',
            name='dynamicnet_count2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrule',
            name='dynamicnet_count3',
            field=models.IntegerField(default=0),
        ),
    ]
