# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0021_auto_20180516_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pretest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pretest_count',
            field=models.IntegerField(default=0),
        ),
    ]
