# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0022_auto_20180517_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPretest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=False)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_pretests', to='trainer.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_pretest', to='trainer.User')),
            ],
        ),
    ]
