# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0023_userpretest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpretest',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Rule'),
        ),
        migrations.AlterField(
            model_name='userpretest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.User'),
        ),
    ]
