# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0024_auto_20180518_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_adaptivity',
            field=models.CharField(default='', max_length=255),
        ),
    ]
