# Generated by Django 2.0.2 on 2018-05-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0025_user_data_adaptivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='origin',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
