# Generated by Django 2.0.2 on 2018-05-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0026_user_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='origin',
            field=models.IntegerField(default=0),
        ),
    ]
