# Generated by Django 3.1.2 on 2020-10-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0026_auto_20201011_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gamification_nickname',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gamification_score',
            field=models.IntegerField(default=0),
        ),
    ]
