# Generated by Django 2.0.2 on 2018-05-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0027_auto_20180525_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTILog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('url', models.CharField(max_length=255)),
                ('sourcedid', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('info', models.TextField(default='')),
                ('mkdate', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.User')),
            ],
        ),
    ]
