# Generated by Django 3.1.2 on 2020-10-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0029_auto_20201011_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_gamification_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='data_gamification_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='data_gamification_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='gamification',
            field=models.IntegerField(choices=[(0, 'Keine Gamification'), (1, 'Level-System'), (2, 'Level-System + individuelles Ranking'), (3, 'Level-System + Gruppen-Ranking')], db_index=True, default=0),
        ),
    ]
