# Generated by Django 3.1.2 on 2020-10-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0030_auto_20201012_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastRecalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
