# Generated by Django 3.1.2 on 2021-10-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0031_lastrecalc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=265, null=True),
        ),
    ]
