# Generated by Django 4.0.2 on 2023-01-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0033_sentence_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='slug',
        ),
    ]
