# Generated by Django 4.0.2 on 2023-01-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0034_remove_rule_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pretest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pretest_count',
        ),
        migrations.RemoveField(
            model_name='userrule',
            name='dynamicnet_active',
        ),
        migrations.RemoveField(
            model_name='userrule',
            name='dynamicnet_count',
        ),
        migrations.RemoveField(
            model_name='userrule',
            name='dynamicnet_count1',
        ),
        migrations.RemoveField(
            model_name='userrule',
            name='dynamicnet_count2',
        ),
        migrations.RemoveField(
            model_name='userrule',
            name='dynamicnet_count3',
        ),
        migrations.RemoveField(
            model_name='userrule',
            name='dynamicnet_current',
        ),
        migrations.RemoveField(
            model_name='userrule',
            name='dynamicnet_history1',
        ),
        migrations.RemoveField(
            model_name='userrule',
            name='dynamicnet_history2',
        ),
        migrations.RemoveField(
            model_name='userrule',
            name='dynamicnet_history3',
        ),
        migrations.RemoveField(
            model_name='userrule',
            name='staticnet',
        ),
        migrations.AlterField(
            model_name='user',
            name='strategy',
            field=models.IntegerField(choices=[(0, 'Leitnerbox')], default=0),
        ),
        migrations.DeleteModel(
            name='UserPretest',
        ),
    ]
