# Generated by Django 4.0.2 on 2023-01-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0035_remove_user_pretest_remove_user_pretest_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrule',
            unique_together={('user', 'rule')},
        ),
    ]
