# Generated by Django 5.2.7 on 2025-10-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0036_alter_userrule_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupHistory',
        ),
        migrations.DeleteModel(
            name='GroupScore',
        ),
        migrations.DeleteModel(
            name='LastRecalc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='data_gamification_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='data_gamification_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='data_gamification_3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gamification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gamification_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gamification_nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gamification_score',
        ),
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
