# Generated by Django 4.2.11 on 2024-11-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0036_alter_userrule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentence',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentence',
            name='part',
            field=models.IntegerField(default=0),
        ),
    ]
