# Generated by Django 4.2.11 on 2024-11-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0037_sentence_extra_sentence_level_sentence_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='excercise_type',
            field=models.IntegerField(default=1),
        ),
    ]
