# Generated by Django 4.2.11 on 2024-11-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0038_sentence_excercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sek2_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='sek2_rule',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='strategy',
            field=models.IntegerField(choices=[(0, 'Leitnerbox'), (1, 'Bayes'), (2, 'SEK2')], default=0),
        ),
    ]
