# Generated by Django 4.2.11 on 2024-11-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0039_user_sek2_level_user_sek2_rule_alter_user_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
