# Generated by Django 4.2.11 on 2024-11-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0040_solution_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='sek2_rule',
            field=models.IntegerField(default=1),
        ),
    ]
