# Generated by Django 4.2.11 on 2024-11-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0041_solution_sek2_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='sek2_level',
            field=models.IntegerField(default=1),
        ),
    ]
